## Introduction

Child Sexual Abuse (CSA) constitutes one of the most severe adverse experiences in child development [@worldhealthorganizationRespondingChildrenAdolescents2017]. The creation, sharing, and viewing of Child Sexual Exploitation Material (CSEM) have increased worldwide in the last years [@baskurtMetaanalysisRecidivismRates2024]. Lifetime prevalence rates of 11.4% for sexual harassment and 8.7% for any form of hands-on sexual violence [@piolantiGlobalPrevalenceSexual2025] demonstrates the high number of victims worldwide. Beyond its profound short- and long-term consequences for survivors, CSA represents a substantial challenge for society due to high economical costs [@kewleyPreventingChildSexual2023]. These figures clearly demonstrate the importance of preventing CSA and CSEM.

<!-- PANEL -->
<!-- Is automatically filled with metadata defined above; do not delete the shortcode -->
{{< panel >}}

In CSA and CSEM prevention, a distinction is commonly drawn between primary, secondary, and tertiary prevention programs. Primary prevention initiatives are directed at children and their parents, whereas secondary prevention programs seek to engage adults identified as being at risk for sexual child offenses, but have not yet been convicted. Tertiary programs have the longest history and are designed for individuals who already committed CSA offenses [@kewleyPreventingChildSexual2023]. In recent years, more and more secondary prevention programs have been implemented worldwide [@setoEvaluatingChildSexual2024]. However, @setoEvaluatingChildSexual2024 identified only five publications exploring the effectiveness of secondary prevention programs for adults, none of them with a methodological high quality. Besides too low sample sizes and the lack of adequate control groups, most of these studies did not provide data on the number of re-offenses based on official criminal records [@kewleyPreventingChildSexual2023]. Thus, currently it is not possible to draw meaningful conclusions on the effectiveness of secondary treatment programs [@setoEvaluatingChildSexual2024]. The effectiveness of tertiary treatment programs for individuals who committed CSA or CSEM has been studied more extensively. Recent meta-meta-analysis (MMA) and meta-analysis demonstrated that cognitive-behavioral treatment programs based on the Risk-Need-Responsivity model [@andrewsPsychologyCriminalConduct2010] are most effective in reducing re-offenses of individuals who have sexually offended. Across meta-analysis, there is consistent evidence for a small but stable treatment effect [@holperModeratorsSexualRecidivism2024; @koehlerMetaevaluativeSynthesisEffects2025; @olverSexualOffenseTreatment2025]. In a recent MMA including 21 meta-analyses on tertiary treatment programs, a treatment effect with an odds ratio (OR) of 0.67, indicating that participants in tertiary treatment programs exhibited approximately a 33% lower risk of recidivism relative to controls was reported [@olverSexualOffenseTreatment2025]. Several moderator variables have been identified: community treatment programs provide higher effect-sizes than institutional treatment programs; individual treatment programs show higher effect-sizes than group programs, high-intensity programs are more effective than low-intensity programs, and the higher the methodological design quality of the study, the lower the effect sizes [@holperModeratorsSexualRecidivism2024; @olverSexualOffenseTreatment2025]. Up to now, most of the mentioned meta-analyses only report on tertiary treatment programs for individuals who have been convicted for CSA. The figure for CSEM is not as well studied. A recent review shed light on the methodological weakness of existing studies on the effectiveness of prevention programs for individuals who have used CSEM: mostly, the studies suffer from small sample sizes, too short follow-up periods and self-reports as main outcome. Besides these limitating factors, the meta-analysis demonstrated preliminary support for the effectiveness of these programs [@gouveiaSystematicReviewEffectiveness2025]. To sum up, meta-analyes demonstrate a broad empirical basis for a small but significant effectiveness in reducing recidivism by tertiary prevention programs for individuals sentenced for CSA. For individuals who have been sentenced for CSEM as well as for secondary prevention programs, the empirical proof of effectiveness is still pending.

Besides this encouraging treatment effects of tertiary intervention programs, there exists a post-release care gap for individuals, who have been sentenced for CSA or CSEM, originating from only having few possibilities of community-based treatment and an increase of convicted ISAC and ICCSEM under community supervision within the last years: For example, @schmidtOutpatientTherapistsPerspectives2022 showed that 63% of n = 427 Swiss outpatient therapists working in the primary healthcare system are unwilling to provide treatment for individuals who have a sexual interest in children and have already been convicted. The study further underlines, that the unwillingness to treat those patients is correlated with stigmatizing attitudes and not feeling to be competent enough. In a German sample, @stiels-glennAvailabilityOutpatientPsychotherapy2010 showed that, 87% of included psychotherapists are not willing to provide treatment, whereas only 2.7% would do so. Furthermore, most of the above mentioned secondary prevention programs, do (at least officially) not accept already convicted ISAC and ICCSEM under CS for treatment [@beierGermanDunkelfeldProject2015]. Additionally to this unwillingness of professionals to treat individuals who have abused a child or consumed child abusive material, the number of individuals convicted for the use of child abusive material, rised in the last years resulting in a increased demand for treatment. In consequence, even if the court ordered treatment, many of convicted ISAC and ICCSEM under CS have difficulties to receive professional treatment during community supervision, especially in rural areas. One possible solution to close this gap is the use of a digital health intervention (DHI) [@hillertWebBasedInitiativesPrevent2024; @wildWebBasedHealthServices2019].

Digital health interventions (DHIs) are assumed to be able to provide a greater accessibility for individuals who face challenges in availing mental health services owing to limited availability or stigma associated with seeking help resulting in reaching a wider population as it is possible with in-face interventions (IFIs). Additionally, the implementation of DHIs is already recommended as a tool to bridge the gap in care for individuals on waiting lists [@crocamoDigitalHealthInterventions2025]. Meta-analysis demonstrated that stand-alone web-based interventions with guidance tend to have greater effect sizes than web-based interventions without professional assistance. Webbased interventions with professional assistance showed smaller attrition rates, a higher number of completed modules, and larger symptom reduction in users [@baumeisterImpactGuidanceInternetbased2014; @heberBenefitWebandComputerbased2017; @cowpertwaitEffectivenessWebbasedPsychological2013; @lehrOccupationalEMentalHealth2016; @richardsComputerbasedPsychologicalTreatments2012]. It is assumed, that DHIs have also the potential to bridge the gap in the care of individuals with regard to tertiary prevention of individuals who have abused a child ore used CSEM [@wildWebBasedHealthServices2019; @hillertWebBasedInitiativesPrevent2024]. To date, studies on the effectiveness of WBIs for individuals who committed CSA or CSEM offenses are scarce [@wildWebBasedHealthServices2019; @hillertWebBasedInitiativesPrevent2024; @schroderWebBasedInterventionsIndividuals2023] . @schroderWebBasedInterventionsIndividuals2023 identified six web-based interventions (WBIs) already implemented in secondary prevention programs, but none implemented in tertiary treatment programs. Furthermore, only one publication reported on the effectiveness of the WBI [@latthEffectsInternetdeliveredCognitive2022]. The authors evaluated a guided WBI exclusively for individuals who commit CSEM offenses in a placobo-controlled RCT. The participants were recruited mainly via Darknet forums and could take part anonymously. The results showed that, compared with users of a psychological placebo WBI (n = 78), participants of the WBI Prevent It (n = 76) reported a statistically significant, but small decrease in weekly viewing of CSEM. Besides of some methodological weakness [@setoEvaluatingChildSexual2024], this study provides first preliminary support for the potential effectiveness of WBIs for CSEM [@hillertWebBasedInitiativesPrevent2024]. For tertiary prevention programs, to the best of our knowledge, there exists no proof of effectiveness for WBIs.

### Aim of the study

In consequence, the study aimed to develop and provide a newly developed WBI to bridge the gap in post-release care of individuals, who have been sentenced for CSA or CSEM. By doing so, the current RCT evaluates the effectiveness of the WBI in reducing dynamic risk factors for re-offending compared to a web-based placebo arm and to evaluate the individual effects of treatment modules within the web-based intervention on reducing dynamic risk factors based on self reports. The primary hypothesis constitutes that participants who take part in the web-based intervention show significantly lower values on dynamic risk factors from baseline to inter-, and post-treatment, compared to an web-based placebo condition. FWe assumed further that, in contrast to the placebo condition, each online module within the intervention arm will reduce the dynamic risk factors targeted in this module in a statistically significant manner.