## Discussion

In this worldwide first randomized placebo-controlled clincial trial of a HBI for individuals who committed sexual offenses against children (tertiary prevention), in contrast to our hypothesis, no significant reduction of risk factors in the intervention arm compared to the placebo arm has been observed on the primary endpoint. Among secondary endpoints, some risk factors showed significant pre–post changes within the intervention arm in line with our hyptheses — most notably, increases in treatment readiness (CVTRQ), decreases in sexual interest in children (ESIQ), and increases in impulsivity-related difficulties (DERS subscale impulsivity) — while the placebo arm showed an isolated improvement in perceived social support (F‑Soz‑U). Between-group difference scores confirmed a significant reduction in explicit sexual interests children in the intervention group, with all other questionnaires yielding non‑significant or non‑robust results. Ancillary analyses demonstrated consistent, statistically robust improvements in working alliance ratings (WAI‑SR) for both online coaches and community supervisors in the intervention group. No comparable changes occurred in the placebo arm. Importingly, no evidence emerged for an increased risk of recidivism or clinically significant deterioration in mental well-being attributable to the intervention. Taken together, the HBI did not lead to measurable changes in the primary CARES outcome but was associated with selected improvements in psychological meaningful risk factors — most notably reduced sexual interest in children and strengthened working alliance with coaches and supervisors — without indications of harm.

The high methodological quality of this clincal trial is underlined by following CODC guidelines for evaluation of sexual offender treatments [@beechCollaborativeOutcomeData2007] as well as the CONSORT guidelines for randomized trials [see @tbl-consort-checklist]. The missing effect on the primary outcome seems to be in line with recent meta-analyses demonstrating, that most rigouros methodological designs showed lowest treatment effects [@holperModeratorsSexualRecidivism2024].

In einem wesentlichen Punkt gelang es uns jedoch nicht die Vorgaben der CODC umzusetzen, da die Studie undersamplet ist. Pro Studienarm hätten 214 Probanden eingeschlossen werden müssen, um auch kleine effektstärken bis d = 0.2 entdeckt werden können. Dies gelang nicht. Auch gelang es nicht, eine repräsentative Stichprobe der Gesamtheit aller Sexualstraftäter in bewährungshilfe zu erheben, da kein uneingeschränkter Zugang zu den klienten möglich war. Dies ist umso bedauerlicher, da es sich um eine bundesweite Stichprobe aus fast allen Bundesländern Deutschlands handelt. Der fehlende direkte Kontakt zu den Probanden führte überdies möglicherweise zu einer selektiven vorauswahl der probanden durch die Bewährungshelfer. Weiterhin konnte aus datenschutzgründen während der Durchführung der Therapie kein direkter Kontakt zu den probanden außerhalb der HBI aufgenommen werden. Dies war nur möglich über den Supervisor, so dass ein direktes nachfragen, wenn beispielsweise längere Zeit kein login erfolgte möglich war. dies könnte sich auch in den, im vergleich zur ursprünglich geplanten dauer der Teilnahme an der klinischen Studie niedergeschlagen haben. Der überwiegend größte Teil ader probanden schaffte es nicht, in der vorgegebenen Zeit die einzelnen Module abzuschließen, mit der konsequenz, dass letztlich der häufigste Ausschlussgrund in einem Ende der klinischen Studie lag. Trotz einer zusätzlichen verlängerung der projektlaufzeit um mehr als ein jahr war es nicht möglich, dasss alle eingeschlossenen Probanden die Teilnahme abschlossen. In letzter Konsequenz gelang es daher auch nicht, eine ausreichend große Stichprobe zu rekrutieren, so dass die Studie als undersampled betrachtet werden muss. Neben schwierigkeiten durch die Corona-Pandemie, gelang es trotz erheblichen rekrutierungsaufwands nicht die angestrebte stichprobengröße zu erreichen, so dass rückblickend klar gesagt werden muss, dass die Schätzungen der verfügbaren Fallzahlen zu optimistisch waren.

Ein weiterer Grund für das Fehlen eines Effektes könnte auch sein, dass es sich in der Merheit der Stichprobe um low-risk Täter handelt. Es ist umstritten ob auch low-risk täter behandelt werden sollte [LIT: SOTP!], jedoch zeigte kürzliche Veröffentlichungen unter anderm im bereich der sekundären prävention, dass dies zu keinem erhöhten Risiko führt [@franqueIndividualsVoluntaryTreatment2023]. Dennoch zeigte sich insbesondere in den sekundären endpoints, für die es normwerte gibt, dass unsere stichprobe sehr häufig oberhalb der norm liegt, so dass davon ausgegangen werden kann, dass der jeweilige Risikofaktor bei vielen Klienten nicht stark ausgeprägt war [Beispiele einfügen oder auf abbildungen verweisen, wenn ich sie denn noch erstelle mit der Vergleichsnorm].

Dies führt zu einem weiteren Kritikpunkte: die HBI folgte nicht konsequent dem RNR-Ansatz, nur beispielsweise ein Modul (kognitive Verzerrungen) bot eine individualisierung des inhaltes an (und alle Übungen + Nachrichten waren individualisiert; nur automatische Nachrichten beispielsweise nach jedem abgeschlossenen gudied Task oder nach jedem abgeschlossenen Modul oder Sitzung erfolgt eine automatische nachricht -> unbedingt in prozess diagramm aufnehmen!). Alle anderen Modulinhalte wurden allen probanden gezeigt, unabhängig davon, ob der Risikofaktor bei einem Klienten vorlag, oder nicht. Dies ist ein klarare Verstoß gegen die RNR Prinzipien und Meta-analysen zeigten, dass diejenigen programme größere Effektstärken zeigen, die nur individuals mit hohem rückfallrisiko in die studie eingeschlossenen haben. Dieses vorgehen ist im Zeiten von personalknappheit auch aus finanziellen Gründen sinnvoll, jedoch bildet die Studie ein realistisches Bild der gegenwärtigen Lage ab: viele individuals mit geringem Risiko erhalten auch eine gerichtliche Therapieweisung, die umgesetzt werden muss. Und für diese Therapieweisung finden sie keine Therapeuten und in dieser Versorgungslücke greift unsere HBI an. Overall, n = 70 (32%) of the ITT sample received an external (f2f) treatment (psychotherapy or medical treatment), but the court ordered this for n = 124 (56%). Only n = 48 (38.71%) of all participants who have an ordered treatment also in fact received external treatment at enrolement, the majority (n = 76; 61.29%) not. This figure underlines the care gap for individuals who committed sexual offenses against children in Germany and their problems to be able to fullfill treatment ordered by court. On the other side, most participants had a low recidivism risk at baseline and it seems to be questionable if the ordered treatment by court is really necessary from an RNR model point of view. But it seems to be not unusual to provide treatment to low-risk sexual offenders in Germany as well as in Canada [@frankeEfficacyOutpatientTreatment2021; @mcpheePracticeSurveyCanadian2025]. Hier könnte auch noch eine größere Dunkelziffer sein, da wir ja kein repräsentatives sample haben.... Auch die baseline characteristics zeigen, dass es sich um eine wenig psychisch belastete population handelt, wie sich anhand des PHQ-D zeigte. Auch der Baseline wert im WHO-5 zeigt ein hohes psychologisches Well-being. Dies steht jedoch im Widerspruch mit der bisherigen Literatur, die in der Regel eine starke psychische Belastung für Personen mit sexuellem Interesse an Kinder aufzeigen [LIT -> Jahnke etc.]. da es sich in unserer Studie aber nur um einen geringen prozentsatz mit einer Diagnose pädophile Störung handelt, scheint die studie zu zeigen, dass es dem Straftäter in der Bewährungshilfe nicht sos chlecht geht.

Ein weiterer Erklrärungsansatz für das fehlen eines Effektes könnte auch darin liegen, dass das primäre outcome, dass zum gegenwärtigen zeitpunkt schon vorliegt, auf Selbstberichten basiert. Selbstberichte sind durchaus umstritten in unserem Bereich. Mögliche Tendenzen zur Antwortverzerrung wurden nicht erhoben, was einen major kritikpunkt an der studie darstellt, und verhindert einen potentiellen Einfluss von Antortverzerrungen in den Analysen zu berücksichtigen. Allerdings steht der Kritik an selbstberichten aufgrund potentieller Impression management eine zunehmende anzahl an studien gegenüber, die selbst-berichten auch hinsichtlich von kriminologischen Faktoren und Rückfallrisiken zu selbstauskünften zeigen [für einen Überblick siehe @sonjaetzlerDevelopmentInitialValidationsubmitted]. Officially recorded reoffenses are generally considered the gold standard for primary outcome assessment in treatment programs for individuals who have sexually offended (LIT). However, official recidivism is a rather insensitive outcome measure for treatment effects because ecidivism rates are low overall, and many offenses remain undetected or unregistered, resulting in low statistical power. Moreover, there is a time lag between the manifestation of deviant behavior and its registration, leading to delayed outcome assessment. Finally, recidivism is a distal measure that provides no insight into the treatment processes of risk reduction. Therefore, several authors have emphasized the importance of examining within-treatment changes in risk factors associated with recidivism [@mannAssessingRiskSexual2010; @olverEvaluatingChangeMen2020]. Des Weiteren ist der CARES ein durchaus neues Tool, dass noch so umfangreich evaluiert ist, insbesondere liegen noch keine Daten zum Zusammenhang zwischen CARES und offiziellen Rückfalldaten vor.

Schließlich könnte auch die Placebo bedingung zu starke effekte hervorrufen, so dass kein unterschied zu sehen ist. so könnte man argumentieren, dass themen wie gesundes essen, gesunder schlaf und sport zu einem - im besten falle - zufriedenerem leben führen. genaus dies ist das ziel im GLM. Möglicherweise fördert die placebo bedingung genau das, was das GLM empfiehlt. Jedoch zeigen sich im WHO-5 keine effekte auf das psychologische wohlbefinden, der beste proxy für zufriedenheit, den wir erfasst haben.

Die Tatsache, dass in Modul 3 die Impulskontrolle bei Placebo abnimmt zeigt, wie wichtig eine evaluation vor der Implementierung auch im forensischen Kontext sinn macht und auch notwendig ist. Beipielsweise sind ganz viele Onlineinterventionen online und werden stark beworben, jedoch liegt keine evaluation vor, so dass nicht sicher ist, ob möglicherwiese mehr Schaden als Gutes angerichtet wird. Die letzte arbeit des projekt dunkelfeldes könnte man in diese Richtung interpretieren!

Fehlender effekt könnte auch an der mangelhaften Umsetzung des Need-Prinzips liegen. Echte anpassung an das ned-prinzip würde bedeuten, dass wir alle prä Fragebögen erheben bei Baseline erheben und dann nur denjenigen entsprechende Module anbieten, wenn ein erhöhter Wert für eine Risikovariable auftritt. dazu müsste man die einzelnen Blöcke der Inhalte, die eine Risikovariable behandeln, zusammenfassen und entweder eine automatisierte oder händische Auswahl derjenigen Inhalte implementieren, die für einen Probanden relevenat sind. Dies wäre sehr gut im rahmen eines blended approaches machbar, der Möglicherwiese das Dropout-Problem reduziert.

Auf Sonjas Ergebnisse sollte man schon auch noch eingehen: Dropout und Gründe für hohen Dropout.

Adverse events...[nochmals mit Lätth et al. vergleichen und schauen, ob e andere Literatur gibt mit diesen Angaben (z.B. SOTP)!]

Unfortunately, none of these statistically significant effects in self-reports reached clinically significance defined by the reliable change index (Jacobson and Truax (1991)). Therefore, the effectiveness of the web-based intervention is questionable.





[Einschätzung der Verschlechterung und der Verbesserungen in Placebo: nicht klinisch relevant, wie ja auch die anderen signifikanten Ergebnisse]

Dauer zu Lange? In Bezug auf Dropouts eigentlich nicht, da Prevent it deutlich kürzer, aber leicht höhere Dropouts. In Bezug auf Empfehlungen zur Behandlung von Sexualstraftäter deutlich zu kurz. Und im Vergleich zu web-based intervention outside offender research viel zu lange.

Bei secondary endpoints nur eine Woche nach dem Modul ende schon die post Messung: der Abstand ist möglicherweise zu gering um schon einen Effekt messen zu können.

Was messen die Fragebögen eigentlich? Zusammenhang zwischen Fragebögen und Rückfall oft gering (Letzte meta-meta analyse), aber sie messen mit hoher wahrscheinlichkeit nur Aspekte der komplexeren Konstrukte Risikovariblen.





The Discussion section should contain a full description and discussion of the context.

• Start with a sentence summarising your main findings and move on to relate your results to your hypothesis and data previously published. Authors must either to report their own, up-to-date systematic review or cite a recent systematic review of other trials as part of a panel putting your research into context with existing evidence (see panel for details). No subheadings should be used in this section.

• Discuss any controversies raised by this study: is sexual interest changeable? McPhail et al. (2020): Hinweis, aber in meta-amalyse keine studie mit adäquater Kontrollgruppe; das können wir nun zeigen, dass auch bei Kontrollgruppendesign eine reduktion möglich ist.

• Discuss the representativeness of the study population, to help readers assess the applicability of the findings to their setting: Due to a possible volunteer-effect, the representativnes of the sample is questionable. On the other side, to the best of our knowledge, this is the first clinical trial in Germany recruiting participants from almost all federal states.

• Consider possible underlying mechanisms for your findings: dropouts because no official document for court;

• Suggest future research directions: comparison to f2f treatment directly or waitlist control;

• State general interpretation of data in light of all evidence available, noting the clinical significance and effects on patient care and policy, expanding on the summary provided in your Research in context panel.



Futere directions: the intervention is currently only available in German. Consequently, the web-based intervention can only be applied in German-speaking countries, which limits its international generalizability.

Second, the study was underpowered to detect small changes. The a priori sample size estimation revelead that 214 participants are necessary in each trial arm in order to be able to detect also effects smaller than d < 0.2 which is in line with the recommendations of the the Collaborative Data Outcome Committee (CODC; @beechCollaborativeOutcomeData2007). Since the proposed sample size has not been reached, there may be a small significant effect in the data we oversee.

Also problematic in this context is the high dropout rate of ??%. Aber nicht so hoch wie bei Prevent it, oder?

Third, the sample cannot be considered representative oder doch ->>>> offizielle Statistiken suchen!!!!!! offizielle statistiken gibt es nicht, es gibt nur jehle, da sind aber nur daten bis 2019 drin, die nicht den zuwachs an KiPo leuten abbildet. da wir die grundgesamtheit aller von den Bewährungshelfenden befragten Personen nicht kennen und kaum jemand den NPQ ausgefüllt hat, können wir einfach nicht wissen, wie repräsentativ die daten sind! Due to a potential volunteer effect, representativeness for the overall population of individuals who have committed child sexual abuse (CSA) or child sexual exploitation material (CSEM) offenses cannot be ensured. Die Probanden erhielten eine aufwandsentschädigung von 120 euro, die aber angesichts der mindestdauer der teilnahme in einen sehr geringen Stundenlohn mündet. Durch die probandenentschädigung war es jedenfalls nicht möglich, einen

Fourth, no waiting-list control group and no face-to-face intervention arm were included. This limits interpretability in two respects. On the one hand, it remains unclear whether the placebo condition might have stronger effects than a waiting-list control group (see relevant literature). On the other hand, the absence of a face-to-face control group prevents conclusions about whether the web-based intervention produces effects comparable to traditional face-to-face interventions, as examined in previous meta-analyses.



Seventh, no assessments of participants’ personal experiences were included. Unfortunately, no feedback was collected from participants regarding the usability of the web-based intervention and the app, nor regarding their subjective experiences during the intervention. This omission limits the evaluation of user acceptance and satisfaction. [ABER: UTAUT ist doch so etwas ähnliches; also die Artikel von Sonja hier rein?]

Eight, no diagnostic was made by staff and therefore, psychiatric disorders only assessed by self reports.

Ausschluss von recidivisten ist nicht so optimal aus klinischer sicht, denn diese hätte es am dringesten nötig



\@myTabu tries to minimize a potential volunteer-bias by providing an adequate allowance.