### Description of trial endpoints {#endpoint-description}

Note that the following description of the primary and secondary outcome moeasures is adapted from @frombergerMyTabuAPlaceboControlled2021.

#### SSQ-P
The SSQ-P is a self developed online questionnaire asking the participants about their demographics, lifestyle, current and former therapeutic treatments and offending history.

#### SSQ-SO
The SSQ-SO is a self-developed online questionnaire for the supervision officer concerning the current living condition, offending and clinical history, and index offense of the participant.

#### SSQ-CF
The SSQ-CF is a self-developed checklist for coding court files. Information from the court files are coded by the study investigators to determine whether the participant meets the study inclusion criteria. This includes information e.g on the index offense, and former offenses. In case that items of the SSQ-CF cannot be filled out adequately by utilizing court files, the participants was interviewed directly.

#### PHQ-D
The PHQ-D [@loeweGesundheitsfragebogenFuerPatienten2002] is a screening tool for mental disorders. Classification of results generally takes place on a syndrome level. Syndromes examined are: Somatoform disorders, major depressive syndrome, other depressive syndrome, panic syndrome, other anxiety syndromes, eating disorder syndrome, alcohol abuse. Tests are scored using a stencil. Utilizing a sum score for each syndrome, conclusions pertaining to the severity of each syndrome can be drawn. The measure shows good to very good diagnostic validity, especially regarding panic disorder and major depression [@graefeScreeningPsychischerStoerungen2004].

#### SSPI-2
The SSPI-2 [@setoRevisedScreeningScale2017a] is a structured rating scale of assessing pedophilic interests based on the offending behavior. It comprises five items (number, age, gender, relationship of victims, and child pornography) and is significantly associated with phallometrically assessed sexual arousal to children. The SSPI-2 is derived from information of the participants as well as the supervision officer and is only defined for hands-on offenders [@setoRevisedScreeningScale2017a].

#### ICD-11-Screener
The ICD-11-Screener [@screenerInstituteSexResearch2019] is a self-assessment procedure to ascertain indications for the presence of sexual dysfunction, gender dysphoria, or paraphilic disorder. However, the instrument is not suitable for diagnosis. It is assumed that the ICD-11-Screener can identify individuals who have the disorders described above. The ICD-11-Screener is not validated yet. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.

#### CARES
The CARES is a composite instrument integrating the CARES-A, which assesses acute dynamic risk factors, and the CARES-S, which measures stable dynamic risk factors [@sonjaetzlerDevelopmentInitialValidationsubmitted]. The CARES total score is calculated by summing the CARES-A and CARES-S total scores, producing a range from 0 to 102, with higher scores indicating greater severity of both acute and stable dynamic risk factors.

The CARES-A scale evaluates seven acute dynamic risk factors associated with sexual reoffending in individuals convicted of at least one (contact or non-contact) sexual offense against children: (1) Preoccupation with Potential Victims, (2) Hostility, (3) Hypersexuality, (4) Rejection of Control Measures, (5) Emotional Crisis, (6) Loss of Social Support, and (7) Substance Use. Comprising 21 items, the CARES-A yields scores from 0 to 42; higher scores denote more pronounced acute dynamic risk. Reliability coefficients for the CARES-A range from $\alpha$ = .79 to $\alpha$ = .83. Analyses of social desirability revealed no significant correlations between CARES-A scores and either the Exaggeration of Positive Qualities or Negative Qualities [@sonjaetzlerDevelopmentInitialValidationsubmitted].

The CARES-S scale assesses six stable dynamic predictors of sexual recidivism. It consists of 30 items covering: (1) Problematic Sexual Interests, (2) Problematic Emotion-Regulation, (3) Lack of Problem-Solving Skills, (4) Offense-Supportive Cognitions, and (5) Lack of Social Support. Five of these subscales correspond to empirically supported psychological risk factors for sexual recidivism [@mannAssessingRiskSexual2010; @setoEmpiricallybasedDynamicRisk2023]. The CARES-S total score ranges from 0 to 60; higher scores indicate stronger stable dynamic risk factors. The reduced CARES-S achieved an internal consistency of $\alpha$ = .53. As with the CARES-A, no significant correlations with social desirability measures were found in the evaluation study [@sonjaetzlerDevelopmentInitialValidationsubmitted].

#### Official re-offences
Officially registered re-offenses will be assessed five years after last-patient-out (September 2030).

#### CVTRQ
The Corrections Victoria Treatment Readiness Questionnaire (CVTRQ) [@caseyAssessingSuitabilityOffender2007] is a self-report measure designed to assess treatment readiness in offenders who have been referred to a cognitive skills program. It comprises 20 items and consists of four scales: (1) Attitudes and motivation, (2) emotional reaction, (3) offending beliefs, and (4) efficacy. Each item has to be answered on a five-point Likert-scale. The CVTRQ shows an acceptable convergent validity, discriminant validity as well as predictive validity [@caseyAssessingSuitabilityOffender2007]. To the best of our knowledge, there is no validated German version of the CVTRQ. \@myTabu translated the CVTRQ. The translation was checked and translated back into English. Resulting differences due to adaptation were inspected and discussed in terms of item content.

#### RCQ
The RCQ [@rollnickDevelopmentShortReadiness1992] is a 12 item questionnaire originally designed to identify the stage of change reached by individuals who excessively drink alcohol. The German version (RCQ-D)[@hannoverReadinessChangeQuestionnaire2002] was adapted within the project by changing the questions regarding drinking of alcohol in questions regarding CSA and CSEM offenses. Responses are made on a five-point Likert-scale. The RCQ-D as well as the RCQ shows good psychometric properties [@hannoverReadinessChangeQuestionnaire2002]. Psychometric properties of the version adapted for ISAC and ICCSEM are not available yet.

#### OQMPR
The QMPR [@merzQuestionnaireMeasurementPsychological1983] is a questionnaire for the assessment of psychological reactance defined as the theory that people resist attempts to constrain either their thoughts or their behaviors. The Optimized Questionnaire for the Measurement of Psychological Reactance (OQMPR)[@herzbergZurPsychometrischenOptimierung2002] is a German variant of the QMPR. The OQMPR consists of 12 statements on a five-point Likert-scale. It has a test-retest-reliability of rtt = 0.85 [@herzbergZurPsychometrischenOptimierung2002].

#### F-SozU
The seven-item short version of F-SozU is an efficient questionnaire to assess perceived social support [@dunkelEvaluationShortformSocial2005]. Each item comprises a five-point Likertscale. Internal consistency of the original long version showed Cronbach's $\alpha$ between 0.81 and 0.93. [@fydrichFragebogenZurSozialen]

#### UCLA
The UCLA [@russellUCLALonelinessScale1996] consists of 20 items in order to assess subjective feelings of loneliness. The German short version [@doringPsychometrischeEinsamkeitsforschungDeutsche1993] consists of 12 items on a four-point Likert-scale. A German study with CSA and CSEM offenders demonstrated a high reliability of $\alpha$ = 0.92. [@neutzeUndetectedDetectedChild2012]

#### DERS
The DERS [@gratzMultidimensionalAssessmentEmotion2004] is a self-report questionnaire to assess emotion dysregulation. The sub-scale "impulse control difficulties" is used as outcome measure and comprises five items on a five-point Likert-scale. The German version is used, which shows a good internal consistency, construct and predictive validity. [@ehringCharacteristicsEmotionRegulation2008]

#### NARQ
The NARQ [@schererNegativeAffectRepair2013] is a self-report questionnaire to assess strategies to regulate negative affect in a systematic manner. It consists of 17 items on a five-point Likert-scale and provides a good construct validity. Reliability scores (Cronbach's $\alpha$) for the three NARQ scales ranged between 0.71 and 0.80. [@schererNegativeAffectRepair2013]

#### BIS-15
The BIS [@pattonFactorStructureBarratt1995] is a questionnaire developed to assess the personality/behavioral construct of impulsiveness. It consists of 30 items on a four-point Likert-scale. The German short version BIS-15 [@meulePsychometrischeEvaluationDeutschen2011] consisting of 15 items is used in the clinical trial. The BIS-15 is an efficient measure of impulsiveness with good internal consistency of $\alpha$ = 0.81.  [@meulePsychometrischeEvaluationDeutschen2011]

#### CUSI
The CUSI [@cortoniSexCopingStrategy2001] is a questionnaire to assess the presence of and the degree to which sex was used to deal with problematic situations. It consists of 16 items on a fivepoint Likert-scale with a satisfying internal consistency [@cortoniSexCopingStrategy2001]. The translation was checked and translated back into English by the authors. Resulting differences due to adaptation were inspected and discussed in terms of item content.

#### SPSI-R
The SPSI-R [@dzurillaSocialProblemSolving2004] is a self-report questionnaire for the assessment of the five dimensions in the social problem-solving model: (1) positive problem orientation, (2) negative problem orientation, (3) rational problem solving, (4) impulsivity/carelessness style, and (5) avoidance style. The SPSI-R consists of 52 items on a five-point Likert-scale. It shows good psychometric properties for individuals who have sexually offended [@wakelingPsychometricValidationSocial2007]. The validated German version is a short form consisting of 25 items [@grafPsychometrischeUeberpruefungDeutschsprachigen2003].

#### BMS
The BMS [@bumbyAssessingCognitiveDistortions] is a self-report questionnaire which assesses offense supportive cognitions of CSA or CSEM offenders (German Version: [@feelgoodKVMSkalaZurErfassung2009]). It consists of 38 items on a four-point Likert-scale. The German version shows good construct validity, internal consistency, and test-retest reliability [@feelgoodKVMSkalaZurErfassung2009].

#### HBI-19
Sexual preoccupation is assessed by the HBI-19 [@kleinValidierungsstudieDeutschenVersion2013]. The HBI-19 is a three-factor measure (coping, control, and consequences) developed to assess hypersexual behavior. The instrument consists of 19 items (e.g., 'I use sex to forget sorrows of everyday life.') answered on a scale from 1 (never) to 5 (very often). The maximum score is 95, with higher scores indicating a higher level of sexual preoccupation. The questionnaire was shown to have good reliability ($\alpha$ = 0.90) and validity [@kleinValidierungsstudieDeutschenVersion2013].

#### SSIC
The SSIC [@tozdanSpezifischeSelbstwirksamkeitZur2015] comprises six items on the participant's conviction regarding the ability to change their sexual interest in children (e.g., 'I can succeed in reducing my sexual interest in children') were answered on a scale from 1 (do not agree at all) to 5 (totally agree). The maximum score is 30, with higher scores indicating a higher level of self-efficacy. The instrument was shown to have good reliability ($\alpha$ = 0.87) and validity [@tozdanSpezifischeSelbstwirksamkeitZur2015].

#### SOI-R
The Item 2a of the SOI-R [@brikenSexualOutletInventory2010] which assesses the desire for sexual activity involving children on a visual analog scale from 0 (desire is absent) to 100 (I have to act to satisfy the desire). Higher values on the scale indicate a stronger sexual interest in children [@brikenSexualOutletInventory2010].

#### EKK-R
Emotional congruence with children is assessed by the EKK-R [@mackEmotionaleKongruenzMit2012] including three factors (special relationship to children, immaturity, and emotional closeness to children). Twenty items are answered on a four-point scale. The questionnaire demonstrated good reliability ($\alpha$ = 0.80) and validity [@mackEmotionaleKongruenzMit2012].

#### ESIQ
The ESIQ [@banseIndirectMeasuresSexual2010] directly assesses pedophilic interest. It consists of two scales measuring sexual behavior (20 items, e.g., 'I enjoyed orally stimulating a man.') and sexual fantasies (20 items, e.g., 'I find it attractive to imagine a little boy sexually stimulating me.'). All items are answered on a scale from 1 (totally disagree) to 5 (totally agree). The reliability of the instrument ranges between 0.86 and 0.97 [@banseIndirectMeasuresSexual2010].

#### WHO-5
The WHO-5 [@bechMeasuringDimensionPsychological2004] is a questionnaire that measures current mental well-being with five items. The items are rated on a six-point Likert-scale ranging from 0 (at no time) to 5 (all of the time). The WHO-5 has shown good validity in measuring subjective well-being in clinical studies [@toppWHO5WellbeingIndex2015]. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.

#### QNP
The Questionnaire of Non-Participation (QNP) was developed to assess reasons for not taking part in the study. It comprises eleven items on a six-point Likert-scale. Items are e.g., 'I will not take part in the study because I do not need any further help.' or 'I will not take part in the study because I am afraid of negative consequences if my SO gets additional information about me.' The QNP will only be administered if a potential participant will not take part in the study but has given informed consent to fill out this questionnaire. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.

#### MRQ
The MRQ consists of ten self-developed items, of which six are asking about thoughts and behaviors associated with potential re-offenses and four asking about the psychological and emotional state of the participant. The MRQ was developed by the \@myTabu team in order to assess adverse events in a structured manner and with adapted adverse events for individuals who have a history of CSA or CSEM. The MRQ has been assessed before and after each session of the WBI and differs between the items in the pre and post measurements: all items of the pre measurement refer explicitly to the time between finishing last post measurement and before starting the new session (time not working on the WBI). The post measurement explicitly asks for the time during working on the session. The MRQ has the following one-item subscales: (1)  Contact planning ("...have you thought about how to best make contact with a child?");  (2) Contact preparation ("...have you made preparations to be able to make contact with a child?"); (3) Urge for CSA ("...have you felt that you must commit a sexual act with a child?"); (4) Urge for CSEM ("...have you felt that you might soon (again) watch child sexual abuse material?"); (5) Sexual tension ("...have you felt that sexual tension has built up within you?)"; (6) Control of sexual thoughts and activity ("...have you felt that it is difficult for you to control your sexual thoughts and activities?"); (7) Unable to cope with the mental burden ("...have you felt that you can no longer endure burdens?"); (8) Suicidal ideations ("...have you thought about taking your own life?"); (9) Mental crisis ("At present, I feel that my behavior and experience are impaired due to mental problems."); (10) Very bad negative mood ("How do you feel at the moment?"). An adverse event was defined as the highest possible score on each one-item self-report subscale ('Often' for subscales 1–8, 'Strongly agree' for subscale 9, and 'Very bad' for subscale 10). The MRQ post questionnaire explicitly asks for the time during working on the WBI, whereas the MRQ pre questionnaire eclusiviely asks for the last week before measurement timepoint. Please note, that the occurence of a report of the highest possible score was defined as adverse event post-hoc. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.

#### WAI-SR
The WAI-SR [@wilmersDeutschsprachigeVersionWorking2008; @horvathDevelopmentWorkingAlliance1986] measures three dimensions of therapeutic alliance: (a) bond, (b) task, and (c) goal. For the purpose of this study, the original items of the German version [@wilmersDeutschsprachigeVersionWorking2008] were adapted to be suitable for a web-based intervention. The items have to be rated on a five-point Likertscale ranging from 1 (never) to 5 (always). It was adapted to suit to the online-coach (WAI-SR COACH) as well as the supervision officer (WAI-SR SUPERVISOR) resulting in 16 items. Internal consistency (Cronbach's $\alpha$) of the original questionnaire ranges from 0.82 to 0.90 [@wilmersDeutschsprachigeVersionWorking2008]. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.

#### EQ
The Exclusion Questionnaire (EQ) is a questionnaire to assess the exclusion reasons of the supervision officer. The EQ was specifically developed for this clinical trial by the project team. Only supervision officers were able to exclude a participant from the trial by clicking a button in the WBI. After clicking the button, the supervision officer had to fill in the EQ before the PI was informed to exclude the participant by Email. The EQ asks about eight possible exclusion reasons (e.g. re-offences, withdraw of informed consent) and one additional free text from. Multiple answers on the eight exclusion reasons are possible. Due to a mistake by the PI, this questionnaire was not mentioned in the SAP.